Repository PaulRBerg/prb-proxy, pull requests merged in 2023-07, with the labels that each got.

#139 refactor: rename deployer to broadcaster
  script/Base.s.sol
  script/DeployDeterministicRegistry.s.sol
  script/DeployProxyViaRegistry.s.sol
  script/DeployRegistry.s.sol
  script/SetPermission.s.sol
Labels: enhancement, feature

#141 refactor: stringify create2 salts
  script/DeployDeterministicRegistry.s.sol
Labels: enhancement

#146 Changes in src/ resulting from the audit
  src/PRBProxy.sol
  src/PRBProxyRegistry.sol
  src/interfaces/IPRBProxy.sol
  src/interfaces/IPRBProxyRegistry.sol
Labels: enhancement

#145 Changes in test/ resulting from the audit
  test/mocks/plugins/PluginReverter.sol
  test/mocks/targets/TargetPayable.sol
  test/mocks/targets/TargetReverter.sol
  test/proxy/Proxy.t.sol
  test/proxy/execute/execute.t.sol
  test/proxy/execute/execute.tree
  test/proxy/receive/receive.t.sol
  test/proxy/run-plugin/runPlugin.t.sol
  test/proxy/run-plugin/runPlugin.tree
  test/registry/deploy-and-execute-and-install-plugin/deployAndExecuteAndInstallPlugin.t.sol
  test/registry/deploy-and-install-plugin/deployAndInstallPlugin.t.sol
  test/registry/deploy-for/deployFor.t.sol
  test/registry/install-plugin/installPlugin.t.sol
  test/registry/set-permission/setPermission.t.sol
  test/registry/set-permission/setPermission.tree
  test/registry/uninstall-plugin/uninstallPlugin.t.sol
  test/registry/uninstall-plugin/uninstallPlugin.tree
Labels: testing

#147 docs: natspec refinements
  src/interfaces/IPRBProxyRegistry.sol
Labels: documentation

#148 feat: add deployment address and explain ABIs
  CONTRIBUTING.md
  README.md
Labels: documentation, enhancement

#150 feat: add deployments json file
  deployments.json
Labels: feature

#161 test: fix "getPermissionByOwner" tests
  test/registry/get-permission-by-owner/getPermissionByOwner.t.sol
Labels: testing

#163 docs: document missing params in NatSpec
  src/interfaces/IPRBProxyRegistry.sol
Labels: documentation

#164 refactor: remove unused errors
  src/interfaces/IPRBProxy.sol
Labels: enhancement

#165 refactor: rename "noProxy" to "onlyNonProxyOwner"
  src/PRBProxyRegistry.sol
  src/interfaces/IPRBProxyRegistry.sol
  test/proxy/Proxy.t.sol
  test/registry/deploy-and-execute-and-install-plugin/deployAndExecuteAndInstallPlugin.t.sol
  test/registry/deploy-and-execute/deployAndExecute.t.sol
  test/registry/deploy-and-install-plugin/deployAndInstallPlugin.t.sol
  test/registry/deploy-for/deployFor.t.sol
  test/registry/deploy/deploy.t.sol
  test/registry/install-plugin/installPlugin.t.sol
  test/registry/set-permission/setPermission.t.sol
  test/registry/uninstall-plugin/uninstallPlugin.t.sol
  test/utils/Precompiles.sol
Labels: enhancement

#166 test: fix "runPlugin" tests
  test/proxy/run-plugin/runPlugin.t.sol
Labels: testing

#169 docs: add audit reports
  audits/cantina-2023-07-11.pdf
  audits/iaro-2023-07-03.pdf
  audits/omniscia-2023-07-10.pdf
Labels: documentation
