Repository PaulRBerg/prb-proxy, pull requests merged in 2023-05, with the labels that each got.

#91 docs: swap deployed addresses
  README.md
Labels: documentation

#92 feat: abstract contract for plugin
  src/PRBProxy.sol
  src/abstracts/PRBProxyPlugin.sol
  src/abstracts/PRBProxyStorage.sol
  src/interfaces/IPRBProxyPlugin.sol
  test/mocks/plugins/PluginChangeOwner.sol
  test/mocks/plugins/PluginDummy.sol
  test/mocks/plugins/PluginEcho.sol
  test/mocks/plugins/PluginEmpty.sol
  test/mocks/plugins/PluginPanic.sol
  test/mocks/plugins/PluginReverter.sol
  test/mocks/plugins/PluginSelfDestructer.sol
  test/mocks/targets/TargetChangeOwner.sol
  test/mocks/targets/TargetDummy.sol
  test/mocks/targets/TargetDummyWithFallback.sol
  test/mocks/targets/TargetEcho.sol
  test/mocks/targets/TargetMinGasReserve.sol
  test/mocks/targets/TargetPanic.sol
  test/mocks/targets/TargetPayable.sol
  test/mocks/targets/TargetReverter.sol
  test/mocks/targets/TargetSelfDestructer.sol
Labels: enhancement, feature

#104 feat: add deterministic deploy scripts
  script/DeployAnnex.s.sol
  script/DeployDeterministicAnnex.s.sol
  script/DeployDeterministicRegistry.s.sol
  script/DeployDeterministicSystem.s.sol
  script/DeployProxyViaRegistry.s.sol
  script/DeployRegistry.s.sol
  script/DeploySystem.s.sol
  test/Base.t.sol
Labels: feature
